# Generated by Django 5.2 on 2025-04-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('company', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=100)),
            ],
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('brand', models.CharField(max_length=100)),
                ('warranty_period', models.IntegerField()),
            ],
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('service_hours', models.CharField(max_length=100)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('listings.listing',),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
