# Generated by Django 5.2 on 2025-04-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_provider',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Poster', 'Poster'), ('Viewer', 'Viewer')], default='Poster', max_length=10),
            preserve_default=False,
        ),
    ]
